# -*- coding: utf-8 -*-
"""AICP_Week06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J7M7ELbs_bvCwrryNDhTBz_I6_AzLtoy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/content/births.csv")

data['Decade'] = (data['year'] // 10) * 10

desc_stats = data.describe()

missing_values = data.isnull().sum()

trend = data.groupby(['Decade', 'gender'])['births'].sum().unstack()
trend.plot(kind='bar', stacked=True)
plt.title('Trend of Male and Female Births Every Decade')
plt.xlabel('Decade')
plt.ylabel('Total Births')
plt.show()

def remove_outliers(data, columns):
  z_scores = np.abs((data[columns] - data[columns].mean()) / data
  data_cleaned = data[(z_scores < 5).all(axis=1)]
  return data_cleaned

data cleaned = remove outliers(data, ['births'])

data['weekday'] = pd.to_datetime(data['day']).dt.day_name()
sns.countplot(data=data, x='weekday', hue='Decade')
plt.title('Births by Weekday for Several Decades')
plt.xlabel('Weekday')
plt.ylabel('Total Births')
plt.xticks(rotation=45)
plt.show()

births_by_month = data.groupby('month')['births'].sum()
births_by_day = data.groupby('day')['births'].sum()

average_births_by_date.index = pd.to_datetime(average_births_by_date)
average_births_by_date = average_births_by_date.dropna()

plt.figure(figsize=(14, 6))
plt.plot(average_births_by_date.index, average_births_by_date.value)
plt.title('Average Number of Births by Date of the Year')
plt.xlabel('Date')
plt.ylabel('Average Number of Births')
plt.grid(True)
plt.show()